[2021-09-29 17:11:18,143][ERROR][WRITE_CSV] invalid number of arguments (check if fb method args are in fb_type.fbt)
[2021-09-29 17:11:18,143][ERROR][WRITE_CSV] Mismatch between array dtype ('<U10') and format specifier ('%.18e')
Traceback (most recent call last):
  File "C:\Users\Rafael\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\lib\npyio.py", line 1435, in savetxt
    v = format % tuple(row) + newline
TypeError: must be real number, not numpy.str_

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Rafael\Documents\dinasore-cluster\dinasore-4\dinasore\core\fb.py", line 59, in run
    outputs = self.fb_obj.schedule(*inputs)
  File "C:\Users\Rafael\Documents\dinasore-cluster\dinasore-4\dinasore\resources\function_blocks\FILES_AND_PLOTS\WRITE_CSV.py", line 39, in schedule
    np.savetxt(f, self.data, delimiter=",")
  File "<__array_function__ internals>", line 5, in savetxt
  File "C:\Users\Rafael\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\lib\npyio.py", line 1437, in savetxt
    raise TypeError("Mismatch between array dtype ('%s') and "
TypeError: Mismatch between array dtype ('<U10') and format specifier ('%.18e')
[2021-09-29 17:11:18,200][ERROR][WRITE_CSV] Mismatch between array dtype ('<U10') and format specifier ('%.18e')
[2021-09-29 17:12:26,167][ERROR][WRITE_CSV] [Errno 13] Permission denied: 'C:\\\\Users\\\\Rafael\\\\Desktop\\\\tmp\\wtv.csv.csv'
[2021-09-29 17:12:26,167][ERROR][WRITE_CSV] [Errno 13] Permission denied: 'C:\\\\Users\\\\Rafael\\\\Desktop\\\\tmp\\wtv.csv.csv'
Traceback (most recent call last):
  File "C:\Users\Rafael\Documents\dinasore-cluster\dinasore-4\dinasore\core\fb.py", line 59, in run
    outputs = self.fb_obj.schedule(*inputs)
  File "C:\Users\Rafael\Documents\dinasore-cluster\dinasore-4\dinasore\resources\function_blocks\FILES_AND_PLOTS\WRITE_CSV.py", line 38, in schedule
    with open(self.path, "a+") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\\\Users\\\\Rafael\\\\Desktop\\\\tmp\\wtv.csv.csv'
